### ISSUE TITLE
Any plans to merge @kurtkotzur's fork?

### ISSUE THREAD

**Issue by rymohr** [heelhook/chardin.js#74]
@heelhook @kurtkotzur any plans to merge back into master? https://github.com/kurtkotzur/chardin.js

I'd like to contribute but it looks like development has stalled here.  Not sure where I should start.

**Comment by heelhook** [comment]
Hey @rymohr 

The PR you mentioned modified the compiled javascript code, instead of the Coffeescript source, so the PR is not really mergeable at this time.

Awesome that you are interested in contributing, if you'd like to take over that PR and integrate the changes in the CoffeeScript source that'd be a great starting point :wink:
