### ISSUE TITLE
Dead repo

### ISSUE THREAD

**Issue by skynet** [heelhook/chardin.js#98]
Is this still maintained? If not, has anyone tried to take over the project. Looks better than Intro.js !
##

**Comment by rhyous** [comment]
I haven't seen any active pulling by the owner since December. Perhaps the owner has moved on? I forked it but I'm not maintaining my branch either. I got it to meet my needs and I moved on.

I actually use both Intro.js and chardin.js in my project.

If you don't want steps, Chardin.js is easier and faster to setup than Intro.js. If you want steps, stick with Intro.js.

I use chardin.js for a full page popup overlay. I use intro.js for a step-by-step walkthru the first time someone logs in. Chardin.js is not designed to do the overlay using step-by-step.

What this project needs is a massive amount of unit tests so changes can be done with a little more stability.

**Comment by joedajigalo** [comment]
Such a great plugin too.

Is there any alternative one would recommend? I love the full page overlay but am having difficulty finding another alternative plugin.

**Comment by rhyous** [comment]
@joedajigalo Does it really matter that this project is not being actively developed? It is open source. My company is using chardin.js in production. The code still exists. It is still further along than starting from scratch. Yes, we had to fix a couple bugs. But the code is still open source. We forked the repo, fixed the bugs, and moved on. In fact, one of the pull requests had a fix I needed, so I didn't even need to fix one of the bugs, I just grabbed the code from the pull request.

**Comment by gbjbaanb** [comment]
It does matter a little, the cdnjs repo is based on this one and if you want to use that, you're stuck with it and no future development (or more importantly, fixes) will be applied. And as there are some great pull requests outstanding, that makes me sad.

**Comment by gbjbaanb** [comment]
No longer dead!
